
package lesson27;

import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author hongyiting
 */
public class MoleJFrame extends javax.swing.JFrame {
    ImageIcon hole  =  new ImageIcon(getClass().getResource("/lesson27/hole.png"));
    ImageIcon mole1 =  new ImageIcon(getClass().getResource("/lesson27/mole1.png"));
    ImageIcon mole2 =  new ImageIcon(getClass().getResource("/lesson27/mole2.png"));
    ImageIcon mole3 =  new ImageIcon(getClass().getResource("/lesson27/mole3.png"));
    ImageIcon mole4 =  new ImageIcon(getClass().getResource("/lesson27/mole4.png"));
    
    ImageIcon[] icons = {hole, mole1, mole2, mole3, mole2, mole1, hole};
    int[] sleepTime = {150, 200, 250, 300, 350, 400, 450, 500};
    MoleRun mr1, mr2, mr3;
    
        class MoleRun implements Runnable {
        private JLabel m, m_message;
        public boolean hit;
        public MoleRun(JLabel m, JLabel m_message) {
            this.m = m;
            this.m_message = m_message;
        }

        @Override
        public void run() {
            for(int i=0;true;i++) {
                int idx = i % icons.length;
                m.setText(idx + "");
                if(hit && idx == 3) { // 是否被打 ?
                    m.setIcon(mole4);
                    m_message.setText("打到我拉~");
                    try {
                        Thread.sleep(3000);
                    } catch (InterruptedException ex) {
                    }
                    i = 0;
                    hit = false;
                } else {
                    hit = false;
                    if(idx == 3) {
                        m_message.setText("來打我啊~");
                    }
                    m.setIcon(icons[idx]);
                    try {
                        int timeIdx = new Random().nextInt(sleepTime.length);
                        Thread.sleep(sleepTime[timeIdx]);
                    } catch (InterruptedException ex) {
                    }
                }
                m_message.setText("打不到我~");
            }
        }
        
    }
    /**
     * Creates new form MoleJFrame
     */
    public MoleJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("打地鼠");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jLabel1.setText("m1");

        jLabel2.setText("m2");

        jLabel3.setText("m3");

        jLabel4.setText("m1_message");

        jLabel5.setText("m2_message");

        jLabel6.setText("m3_message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton1)
                        .addGap(89, 89, 89)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel4)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel5)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel6)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mr1 = new MoleRun(m1, m1_message);
        mr2 = new MoleRun(m2, m2_message);
        mr3 = new MoleRun(m3, m3_message);
        
        new Thread(mr1).start();
        new Thread(mr2).start();
        new Thread(mr3).start();
        
        }//GEN-LAST:event_jButton1ActionPerformed

    private void m1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m1MousePressed
        mr1.hit = true;
    }//GEN-LAST:event_m1MousePressed

    private void m2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m2MousePressed
        mr2.hit = true;
    }//GEN-LAST:event_m2MousePressed

    private void m3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_m3MousePressed
        mr3.hit = true;
    }//GEN-LAST:event_m3MousePressed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MoleJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
